version: "2"
plugins:
  shellcheck:
    enabled: true
  govet:
    enabled: true
  gofmt:
    enabled: true
  golint:
    enabled: true
  fixme:
    enabled: true

checks:
  argument-count:
    enabled: true
    config:
      threshold: 6
  method-lines:
    enabled: true
    config:
      threshold: 50
  return-statements:
    enabled: true
    config:
      threshold: 10
  similar-code:
    enabled: true
  identical-code:
    enabled: true

exclude_patterns:
- 'config/'
- 'db/'
- 'dist/'
- 'features/'
- '**/node_modules/'
- 'script/'
- 'envtest/'
- '**/spec/'
- '**/test/'
- '**/tests/'
- 'Tests/'
- '**/vendor/'
- '**/*_test.go'
- '**/*.d.ts'
- 'e2e/lib/'
- '**/zz_generated.deepcopy.go'
